### ISSUE TITLE
./consul_lock_test.sh: line 200: service: unbound variable

### ISSUE THREAD

**Issue by chrisumbel** [fidian/consul-locker#3]
When running consul_lock_test.sh I see the following error: 
./consul_lock_test.sh: line 200: service: unbound variable

I couldn't track down a $service variable but certainly do see a $serviceName variable. Should $service be $serviceName instead? That change seems to allow me to get around the error, but I'm concerned I'm missing some context.

**Comment by fidian** [comment]
You're exactly right.  I've made the change you suggested.

I am sorry that the script didn't work immediately for you.  I forgot to backport this exact same change when it was discovered in the copy that my work uses.
